/**
 * The provenance line must be the LAST thing on the page, in every template.
 *
 * It used to be a bare `<footer>` with a top margin, so it stopped wherever the
 * content stopped: on a sparse profile — a new candidate with no experience and
 * no skills yet, which is the common first render here — it landed halfway up an
 * otherwise blank page and read as a document that had been cut off.
 *
 * `stickyFooterFrame()` in ./shared fixes it, but a fix in a shared helper is
 * only as good as its adoption: a new template that hand-rolls its own footer,
 * or forgets the `<main>` wrapper the auto margin needs, silently reverts to the
 * old behaviour and nothing else in the suite notices. So this asserts the
 * CONTRACT on every registered template rather than on the four that existed
 * when it was written.
 *
 * Checked structurally rather than by rendering a PDF and measuring: the
 * geometry was verified once against real A4 output (footer flush at the page
 * bottom, still one page), and what regresses afterwards is a template dropping
 * the mechanism — which is exactly what the markup shows.
 */
import { ResumeTemplate } from '@prisma/client';
import { ResumeSource } from '../../candidate/candidate-read.service';
import {
  RESUME_SETTINGS_DEFAULTS,
  ResumeRenderSettings,
  toResumeView,
} from '../resume-view.mapper';
import { TEMPLATE_REGISTRY } from './registry';
import { ACCEPTED_RESUME_TEMPLATES } from '../dto/update-resume-settings.dto';

const settings: ResumeRenderSettings = { ...RESUME_SETTINGS_DEFAULTS, showPhone: true };

/**
 * Deliberately the THINNEST profile that can exist: the email is the only
 * mandatory field. This is the shape that exposed the bug.
 */
const bare = {
  id: 'c1',
  fullName: 'A Candidate',
  fatherName: null,
  dob: null,
  phone: null,
  maritalStatus: null,
  religion: null,
  languages: [],
  currentLocation: null,
  nationality: null,
  photoKey: null,
  videoR2Key: null,
  jobCategory: null,
  user: { email: 'a@example.com' },
  experiences: [],
  skills: [],
  documents: [],
} as unknown as ResumeSource;

const templates = Object.keys(TEMPLATE_REGISTRY) as ResumeTemplate[];

describe.each(templates)('%s — provenance footer placement', (template) => {
  const html = TEMPLATE_REGISTRY[template](toResumeView(bare, settings, null));

  it('carries the sticky-footer layout', () => {
    // The three rules that do the work. Asserted together because any one of
    // them missing silently un-pins the footer.
    expect(html).toContain('display: flex');
    expect(html).toContain('flex-direction: column');
    expect(html).toMatch(/footer \{[^}]*margin-top: auto/);
  });

  it('wraps its content in <main> so the auto margin has room to grow', () => {
    // Without a growing element between header and footer there is no leftover
    // space for `margin-top: auto` to consume, and the footer rides up with the
    // content again.
    expect(html).toContain('<main');
    expect(html).toMatch(/<main[\s\S]*<\/main>/);
    expect(html).toMatch(/main \{[^}]*flex: 1 0 auto/);
  });

  it('renders the footer LAST — after </main>, immediately before </body>', () => {
    const mainEnd = html.lastIndexOf('</main>');
    const footerStart = html.indexOf('<footer');
    expect(mainEnd).toBeGreaterThan(-1);
    expect(footerStart).toBeGreaterThan(mainEnd);

    // Nothing but whitespace may follow the footer inside the body — an element
    // after it would print BELOW the provenance line.
    const tail = html.slice(html.indexOf('</footer>') + '</footer>'.length);
    expect(tail.replace(/\s/g, '')).toBe('</body></html>');
  });

  it('states its provenance exactly once', () => {
    expect(html.match(/Generated by Skill India Connect/g)).toHaveLength(1);
    expect(html.match(/<footer/g)).toHaveLength(1);
  });

  it('is a template the API will actually accept', () => {
    /*
      The gap that shipped three templates the picker offered and the API
      refused: the Prisma enum, the contract and the gallery all gained
      ELEGANT/EXECUTIVE/TIMELINE while `ACCEPTED_RESUME_TEMPLATES` still held
      the original four, so choosing one returned "That resume template is not
      available yet." Nothing failed — the DTO list was simply a fifth place the
      set was written down.

      Asserted per template so the failure names the one that is unreachable.
    */
    expect(ACCEPTED_RESUME_TEMPLATES).toContain(template);
  });
});
