/**
 * The only things four resume templates are allowed to share.
 *
 * Deliberately small. Sharing the ESCAPING and the PAGE FRAME is necessary;
 * sharing anything visual would make the templates stop being distinct, which
 * is the entire point of offering a choice.
 */
import { ResumeViewDto } from '../resume-view.mapper';

/**
 * THE escaping function — one definition, imported by every template.
 *
 * Not copy-pasted per template on purpose. Four private copies of an escaping
 * routine is a security-relevant duplication: one copy drifts, misses a
 * character, and a company name containing `<` injects markup into the render
 * context. Profile text is user input in every field a template touches.
 */
export function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * The photo, validated and escaped, or null.
 *
 * SEC-004 (S8-H2): photoDataUri is the ONE value that lands in an ATTRIBUTE
 * rather than in text. A URI containing a double-quote would close src="" and
 * the remainder becomes attributes — `data:image/png" onload="alert(1)` yields
 * a live handler executing inside the Chromium render context.
 *
 * Not reachable today (the URI is built server-side from an R2 fetch and no
 * endpoint lets a candidate set it), but it is a landmine rather than a live
 * hole, and it must be defused in ONE place rather than in each template —
 * a template that forgot this guard would reintroduce the whole issue.
 *
 * Two independent guards because either alone would do and both are cheap:
 * shape-validate that it really is a data: image URI, and esc() it so a quote
 * can never terminate the attribute.
 */
export function safePhotoSrc(view: ResumeViewDto): string | null {
  const uri = view.photoDataUri;
  if (!uri) return null;
  return /^data:image\/[a-zA-Z0-9.+-]+;base64,[A-Za-z0-9+/=]*$/.test(uri) ? esc(uri) : null;
}

/**
 * A4 page setup + the reset every template starts from.
 *
 * The MARGINS are intentionally not fixed here — whitespace is a large part of
 * what distinguishes MINIMAL from COMPACT — so each template passes its own.
 */
export function pageFrame(margin: string): string {
  return `
  @page { size: A4; margin: ${margin}; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  /* Nothing may bleed across an A4 boundary mid-item. */
  section { break-inside: auto; }
  li, tr { break-inside: avoid; }
  h1, h2, h3 { break-after: avoid; }
  img { max-width: 100%; }
  /* Long unbroken tokens (a URL-ish company name) must wrap, never overflow. */
  body { overflow-wrap: anywhere; word-break: normal; }
`;
}

/**
 * The provenance line every template ends with, and the layout that pins it to
 * the BOTTOM of the last page.
 *
 * It used to be `<footer>` with nothing but a `margin-top`, so it sat wherever
 * the content happened to stop. On a full resume that is the bottom of the page;
 * on a sparse one — a candidate with two skills and no overseas experience, i.e.
 * exactly the new joiner most likely to look at their first PDF — it landed
 * halfway up an otherwise blank page and read as if the document had been cut
 * off mid-render.
 *
 * The mechanism is the classic sticky footer, which behaves in Chromium's print
 * path the same way it does on screen: `html` is one page tall, `body` is at
 * least that tall, `main` grows, and `margin-top: auto` on the footer eats the
 * leftover space. When the content DOES overflow to a second page the auto
 * margin collapses to nothing and the footer simply follows the content on the
 * last page, which is the wanted behaviour there too.
 *
 * Deliberately NOT `position: fixed`, the other obvious way to pin something in
 * print: fixed elements REPEAT on every page in Chromium, so a two-page resume
 * would claim to have been generated twice.
 *
 * Shared rather than restated per template because it is provenance, not design
 * — and because four hand-written copies is how the drift above started.
 */
export function stickyFooterFrame(): string {
  return `
  html { height: 100%; }
  body { min-height: 100%; display: flex; flex-direction: column; }
  /* Grows to fill the page so the auto margin below has space to consume. */
  main { flex: 1 0 auto; }
  footer { flex: 0 0 auto; margin-top: auto; }
`;
}

/** The provenance line itself. Identical text in every template. */
export function documentFooter(view: ResumeViewDto): string {
  return `<footer>Generated by Skill India Connect &middot; ${esc(view.generatedAt.slice(0, 10))}</footer>`;
}

/** Human label for a document type — shared because it is data, not design. */
export function documentLabel(type: string): string {
  switch (type) {
    case 'PASSPORT':
      return 'Passport';
    case 'EXPERIENCE_CERT':
      return 'Experience certificate';
    case 'EDUCATIONAL_CERT':
      return 'Educational certificate';
    default:
      return type;
  }
}

/** "4 yr 2 mo" / "" — shared formatting, each template decides where it goes. */
export function durationLabel(years: number, months: number): string {
  const parts: string[] = [];
  if (years > 0) parts.push(`${years} yr`);
  if (months > 0) parts.push(`${months} mo`);
  return parts.join(' ');
}

/**
 * The personal-detail rows a template may show, already filtered.
 *
 * Returns ONLY what the ResumeView actually carries. A field the mapper omitted
 * is simply absent from the view, so it never appears in this list and no
 * template can render a label for a value it does not have — that is how "no
 * empty Passport number: row" holds for every template without each one
 * reimplementing the check.
 */
export function factRows(view: ResumeViewDto): Array<[string, string]> {
  const rows: Array<[string, string]> = [];
  if (view.fatherName) rows.push(["Father's name", view.fatherName]);
  if (view.dob) rows.push(['Date of birth', view.dob]);
  if (view.nationality) rows.push(['Nationality', view.nationality]);
  if (view.maritalStatus) rows.push(['Marital status', view.maritalStatus]);
  if (view.religion) rows.push(['Religion', view.religion]);
  if (view.languages.length > 0) rows.push(['Languages', view.languages.join(', ')]);
  if (view.passportNumber) rows.push(['Passport number', view.passportNumber]);
  return rows;
}

/** email · phone · location — only the parts the view carries. */
export function contactParts(view: ResumeViewDto): string[] {
  const parts = [view.email];
  if (view.phone) parts.push(view.phone);
  if (view.currentLocation) parts.push(view.currentLocation);
  return parts;
}
